### ISSUE TITLE
Typoscript doesn't seem to work

### ISSUE THREAD

**Issue by mewcrazy** [o-ba/custom_dashboard_widgets#2]
Hi Oliver,

I know this isn't really a bug related to your extension, but I tried to create my own dashboard, widget group and widget according to your example extension. So far everything is working as expected. But the widget doesn't seem to use the Templates defined in TypoScript.

I use the following TypoScript, but the templates are not showing up.
`
#
# Dashboard
#
module.tx_dashboard {
   view {
       templateRootPaths {
           111 = EXT:my_extension/Resources/Private/Templates/Dashboard/Widgets/
       }
       partialRootPaths {
           111 = EXT:my_extension/Resources/Private/Partials/Dashboard/Widgets/
       }
   }
}`

Do you have any idea what other steps are neccessary to get the widget templates up and running?

Kind Regards,
Dennis Bitsch

**Comment by o-ba** [comment]
Hi, there could be a couple of reasons. So some question from my side:

1. How do you include the TypoScript?
2. Do you correctly set the template in your widget?
3. Have you checked whether the paths are correct?
4. Do you get any error message / exception?

**Comment by mewcrazy** [comment]
Hi, thanks for taking the time.

1. First I tried my main setup.typoscript -> no effect, then I tried Template->Setup of my root page -> also no effect.
![image](https://user-images.githubusercontent.com/6299479/168935306-470e7109-7ffe-4616-8c55-17fd93294d8f.png)
2. I think so. In my renderWidgetContent() method in RecentOrdersWidget.php I got the following: $this->view->setTemplate('Widget/RecentOrdersWidget');
![image](https://user-images.githubusercontent.com/6299479/168935042-71363b12-9e99-4d64-8898-ce358f6183f1.png)
3. The above paths are definitly correct. After looking at the error message it seems as if there are no paths set at all.
5. Yes, take a look:
![image](https://user-images.githubusercontent.com/6299479/168934825-8d49416d-b330-4675-8bac-e33824caf195.png)



Btw: I'm using TYPO3 v11. Maybe something changed?

**Comment by o-ba** [comment]
> The above paths are definitly correct. After looking at the error message it seems as if there are no paths set at all.

Are the core widgets working?

Could you please try to include the TypoScript globally with `ExtensionManagementUtility::addTypoScriptSetup()` in your `ext_localconf.php`, like done by this extension: https://github.com/o-ba/custom_dashboard_widgets/blob/main/ext_localconf.php#L8

**Comment by mewcrazy** [comment]
Hi, well I tried to include it via addTypoScriptSetup() - But the result is the same as with ::addStaticFile().

But then I had a lucky find while looking at the StandaloneView class. It's possible to set the Template/Layout/Partial Paths via PHP. And it worked right away. The widget is showing up.

$this->view->setTemplateRootPaths(['EXT:ext/Resources/Private/Templates/Dashboard/']);
$this->view->setLayoutRootPaths(['EXT:ext/Resources/Private/Templates/Dashboard/']);
$this->view->setPartialRootPaths(['EXT:ext/Resources/Private/Templates/Dashboard/']);

Thanks again for the help 👌

**Comment by andreknieriem** [comment]
Sorry, but this is not done. My typoscript is shown in Backend but the path to the template is not taken.
