### ISSUE TITLE
Support TYPO3 v12 / PHP 8

### ISSUE THREAD

**Issue by konradmichalik** [o-ba/custom_dashboard_widgets#4]
Hej there,
is the support for TYPO3 v12 and PHP 8+ planned?
Cheers

**Comment by o-ba** [comment]
Hi, yes it's planned to release a compatible version.

**Comment by o-ba** [comment]
Hi, a compatible [version](https://github.com/o-ba/custom_dashboard_widgets/releases/tag/1.3.0) was released today. I'll therefore close this issue. Thanks for your reminder. 👍

**Comment by konradmichalik** [comment]
Thanks for the fast release.
